name: flow-with-norm-build-tests

on:
  push:
      branches:
        - master
  pull_request:
    branches: [ "master" ]

jobs:
  norminette:
    name: norminette
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: install dependencies 
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install norminette 
      
      - name: Test with norminette
        run: norminette

  build:
    name: build
    needs: norminette
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      
      - name: Make Mandatory
        run: make
  
  test01:
    name: Test Tripouille - Mandatory
    needs: build
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2

      - name: install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install valgrind -y

      - name: Cloning Tester Tripouille - Mandatory
        run: |
          git clone https://github.com/Tripouille/libftTester.git
          cd libftTester
          export TERM=xterm-256color
          make m